[language_servers.pylsp]
enable_ruff = true
enable_mypy = true
enable_pyflakes = false
enabled = false
enable_pylint = false
enable_pydocstyle = false
enable_flake8 = false

[language_servers.basedpyright]

[language_servers.ty]

[runtime]
std_stream_max_bytes = 1000000
auto_instantiate = false
reactive_tests = true
watcher_on_save = "lazy"
auto_reload = "off"
default_sql_output = "auto"
dotenv = []
default_auto_download = []
on_cell_change = "autorun"
output_max_bytes = 8000000

[package_management]
manager = "uv"

[server]
browser = "default"
follow_symlink = false

[ai]
mode = "manual"
inline_tooltip = false
rules = ""

[ai.models]
custom_models = []
displayed_models = []

[save]
autosave_delay = 1000
format_on_save = false
autosave = "after_delay"

[display]
reference_highlighting = false
cell_output = "below"
default_table_page_size = 10
theme = "dark"
code_editor_font_size = 14
default_width = "medium"
default_table_max_columns = 50
dataframes = "rich"

[snippets]
custom_paths = []
include_default_snippets = true

[mcp]
presets = []

[mcp.mcpServers]

[formatting]
line_length = 79

[experimental]

[diagnostics]
sql_linter = true

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[completion]
copilot = false
activate_on_typing = true
