[completion]
activate_on_typing = true
copilot = false

[datasources]

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[diagnostics]
sql_linter = true

[runtime]
on_cell_change = "autorun"
watcher_on_save = "lazy"
auto_instantiate = false
dotenv = []
default_sql_output = "auto"
auto_reload = "off"
default_auto_download = []
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
reactive_tests = true

[mcp]
presets = []

[mcp.mcpServers]

[display]
reference_highlighting = false
default_width = "medium"
cell_output = "below"
default_table_page_size = 10
theme = "dark"
default_table_max_columns = 50
code_editor_font_size = 14
dataframes = "rich"

[formatting]
line_length = 79

[save]
autosave_delay = 1000
format_on_save = false
autosave = "off"

[snippets]
custom_paths = []
include_default_snippets = true

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enable_ruff = true
enable_pydocstyle = false
enable_flake8 = false
enabled = false
enable_pyflakes = false
enable_mypy = true
enable_pylint = false

[ai]
inline_tooltip = false
mode = "manual"
rules = ""

[ai.models]
displayed_models = []
custom_models = []

[server]
browser = "default"
follow_symlink = false

[experimental]

[package_management]
manager = "uv"
