[snippets]
custom_paths = []
include_default_snippets = true

[runtime]
auto_instantiate = false
auto_reload = "off"
reactive_tests = true
on_cell_change = "autorun"
watcher_on_save = "lazy"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
default_sql_output = "auto"
default_csv_encoding = "utf-8"

[display]
theme = "light"
code_editor_font_size = 14
cell_output = "below"
default_width = "medium"
dataframes = "rich"
default_table_page_size = 10
default_table_max_columns = 50
reference_highlighting = true

[server]
browser = "default"
follow_symlink = false

[save]
format_on_save = false
autosave = "off"
autosave_delay = 1000

[ai.models]
displayed_models = []
custom_models = []

[ai.custom_providers]

[diagnostics]
sql_linter = true

[package_management]
manager = "uv"

[mcp]
presets = []

[mcp.mcpServers]

[completion]
activate_on_typing = true
signature_hint_on_typing = false
copilot = false

[keymap]
preset = "default"

[keymap.overrides]

[formatting]
line_length = 79

[language_servers.pylsp]
enabled = false
enable_mypy = true
enable_ruff = true
enable_flake8 = false
enable_pydocstyle = false
enable_pylint = false
enable_pyflakes = false
