[diagnostics]
sql_linter = true

[ai.models]
custom_models = []
displayed_models = []

[ai.custom_providers]

[formatting]
line_length = 79

[runtime]
reactive_tests = true
on_cell_change = "autorun"
auto_instantiate = false
auto_reload = "off"
default_sql_output = "auto"
default_csv_encoding = "utf-8"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"

[save]
autosave = "off"
format_on_save = false
autosave_delay = 1000

[package_management]
manager = "uv"

[snippets]
custom_paths = []
include_default_snippets = true

[language_servers.pylsp]
enable_pydocstyle = false
enabled = false
enable_ruff = true
enable_flake8 = false
enable_pyflakes = false
enable_mypy = true
enable_pylint = false

[keymap]
preset = "default"

[keymap.overrides]

[completion]
activate_on_typing = true
signature_hint_on_typing = false
copilot = false

[display]
cell_output = "below"
reference_highlighting = true
code_editor_font_size = 14
dataframes = "rich"
default_width = "medium"
theme = "light"
default_table_max_columns = 50
default_table_page_size = 10

[server]
follow_symlink = false
browser = "default"

[mcp]
presets = []

[mcp.mcpServers]
